'use strict';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),DAY=864e5,pad=n=>String(n).padStart(2,'0');
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const startOfDay=ts=>{const d=new Date(ts);d.setHours(0,0,0,0);return d.getTime();};
const localDateKey=ts=>{const d=new Date(ts);return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;};
const eventDateKey=e=>e.localDate||localDateKey(e.t);
const keyToTs=k=>{const[a,b,c]=k.split('-').map(Number);return new Date(a,b-1,c).getTime();};
const eventHour=e=>Number.isInteger(e.localHour)?e.localHour:new Date(e.t).getHours();
const fmtHM=ts=>{const d=new Date(ts);return pad(d.getHours())+':'+pad(d.getMinutes());},fmtMD=ts=>{const d=new Date(ts);return(d.getMonth()+1)+'月'+d.getDate()+'日';};
const CN='一二三四五六七八九十';function cnNum(n){if(n<=10)return CN[n-1];if(n<20)return'十'+CN[n-11];const t=Math.floor(n/10),o=n%10;return CN[t-1]+'十'+(o?CN[o-1]:'');}const cnDate=d=>cnNum(d.getMonth()+1)+'月'+cnNum(d.getDate())+'日',cnWeek=d=>'星期'+'日一二三四五六'[d.getDay()];
function fmtDur(ms){const m=Math.floor(ms/6e4);if(m<1)return'刚刚';if(m<60)return m+' 分钟';const h=Math.floor(m/60);if(h<48)return h+' 小时'+(m%60?' '+m%60+' 分':'');return Math.floor(h/24)+' 天'+(h%24?' '+h%24+' 小时':'');}
let events=[],prefs={limit:{on:false,days:1,cigs:10},limitTouched:false},cur='today',statsRange=30,histDays=14,manageMode=false,selected=new Set(),histVisible=[],lastEv=null,undoTimer=null,recordLock=false;
function mergePrefs(p){p=p&&typeof p==='object'?p:{};const l=p.limit&&typeof p.limit==='object'?p.limit:{};return{limit:{on:l.on!==false,days:Math.min(7,Math.max(1,Math.round(l.days||1))),cigs:Math.min(20,Math.max(1,Math.round(l.cigs||10)))},limitTouched:!!p.limitTouched};}
function makeEvent(ts){const d=new Date(ts);return{id:uid(),t:ts,localDate:localDateKey(ts),localHour:d.getHours(),tzOffset:d.getTimezoneOffset()};}
async function addEvent(ts){const ev=makeEvent(ts);events.push(ev);events.sort((a,b)=>a.t-b.t);await DB.putEvent(ev);return ev;}
function firstDay(){return events.length?Math.min(...events.map(e=>keyToTs(eventDateKey(e)))):null;}
function dayCount(from){const f=firstDay();if(f===null)return 0;return Math.round((startOfDay(Date.now())-Math.max(f,from||f))/DAY)+1;}
function eventsFrom(days){if(days===Infinity)return events;const cutoff=startOfDay(Date.now())-(days-1)*DAY;return events.filter(e=>keyToTs(eventDateKey(e))>=cutoff);}
function hourlyBins(days){const b=Array(24).fill(0);eventsFrom(days).forEach(e=>b[eventHour(e)]++);return b;}
function openSheet(sel){$('#mask').classList.add('show');$(sel).classList.add('show');}function closeSheet(){$('#mask').classList.remove('show');$$('.sheet').forEach(s=>s.classList.remove('show'));}
let confirmRes=null;function confirmSheet(title,body,okText){return new Promise(res=>{$('#cfTitle').textContent=title;$('#cfBody').textContent=body;$('#cfOk').textContent=okText;openSheet('#sheetConfirm');confirmRes=res;$('#cfOk').onclick=()=>{closeSheet();confirmRes=null;res(true);};$('#cfCancel').onclick=()=>{closeSheet();confirmRes=null;res(false);};});}
let toastT=null;function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastT);toastT=setTimeout(()=>t.classList.remove('show'),2200);}
function renderToday(){const now=Date.now(),sod=startOfDay(now),d=new Date(now),todayKey=localDateKey(now),today=events.filter(e=>eventDateKey(e)===todayKey),n=today.length,L=prefs.limit,use=prefs.limitTouched&&L.on;let cnt=0;if(use){const cut=sod-(L.days-1)*DAY;cnt=events.filter(e=>keyToTs(eventDateKey(e))>=cut).length;}$('#todayDate').textContent=cnDate(d)+' · '+cnWeek(d);$('#todayNum').textContent=n;$('#todayNum').classList.toggle('over',use&&cnt>=L.cigs);let st='今日';if(use)st=cnt>L.cigs?`超出上限 ${cnt-L.cigs} 支`:cnt===L.cigs?'已达上限':`今日 · ${cnt}/${L.cigs} 支`;$('#todaySub').textContent=st;$('#todaySub').classList.toggle('warn',use&&cnt>=L.cigs);$('#limitWrap').style.display=use?'':'none';if(use){$('#limitBar i').style.width=Math.min(100,cnt/L.cigs*100)+'%';$('#limitBar').classList.toggle('over',cnt>=L.cigs);}$('#limitMini').textContent=use?`周期上限 · 每${L.days}天${L.cigs}支`:(prefs.limitTouched?'周期上限 · 未启用':'周期上限 · 未设置');const last=events.length?events[events.length-1].t:null;$('#statLast').textContent=last?fmtDur(now-last):'—';const c30=eventsFrom(30).length,sp=dayCount();$('#statAvg').textContent=events.length&&sp?(c30/Math.min(30,sp)).toFixed(1)+' 支':'—';const bins=hourlyBins(30),mx=Math.max(...bins);const peaks=bins.map((v,i)=>v===mx&&v?i:null).filter(v=>v!==null);$('#peakLine').textContent=!events.length?'按下圆章，记下第一支烟':mx>=3?`近30日，高峰常在 ${peaks.slice(0,3).join('、')} 时前后`:'再记录几天，高峰时段就会浮现';}
function buildTrend(){if(!events.length)return{data:[],ma:0};const first=firstDay(),last=startOfDay(Date.now()),days=Math.round((last-first)/DAY)+1;let step=1;if(statsRange===Infinity&&days>730)step=30;else if(statsRange===Infinity&&days>180)step=7;const from=statsRange===Infinity?first:Math.max(first,last-(statsRange-1)*DAY);const buckets=[];for(let t=from;t<=last;t+=step*DAY)buckets.push({day:t,c:0});events.forEach(e=>{const t=keyToTs(eventDateKey(e));if(t<from)return;const i=Math.min(buckets.length-1,Math.floor((t-from)/(step*DAY)));if(i>=0)buckets[i].c++;});const ma=statsRange===7?0:statsRange===30?5:statsRange===90?10:Math.max(2,Math.round(buckets.length/10));if(ma)buckets.forEach((p,i)=>{let s=0,c=0;for(let j=Math.max(0,i-ma+1);j<=i;j++){s+=buckets[j].c;c++;}p.m=s/c;});return{data:buckets,ma,step};}
function renderStats(){const R=statsRange,sod=startOfDay(Date.now()),s0=R===Infinity?0:sod-(R-1)*DAY,inR=events.filter(e=>R===Infinity||keyToTs(eventDateKey(e))>=s0),total=inR.length,days=Math.max(1,R===Infinity?dayCount():Math.min(R,dayCount(s0)));$('#ovTotal').textContent=total;$('#ovTotalL').textContent=(R===Infinity?'全部':`近${R}日`)+' 总计';$('#ovAvg').textContent=events.length?(total/days).toFixed(1):'—';const dayCnt={};inR.forEach(e=>{const k=eventDateKey(e);dayCnt[k]=(dayCnt[k]||0)+1;});let top=null;Object.entries(dayCnt).forEach(([k,c])=>{if(!top||c>top.c)top={k,c};});$('#ovTop').textContent=top?`${fmtMD(keyToTs(top.k))} · ${top.c} 支`:'—';let min=null;if(events.length){const from=R===Infinity?firstDay():Math.max(firstDay(),s0);for(let t=from;t<=sod;t+=DAY){const k=localDateKey(t),c=dayCnt[k]||0;if(!min||c<min.c)min={t,c};}}$('#ovMin').textContent=min?`${fmtMD(min.t)} · ${min.c} 支`:'—';const cmp=$('#ovCmp');cmp.className='';let ct='—';if(R!==Infinity){const ps=s0-R*DAY,prev=events.filter(e=>{const t=keyToTs(eventDateKey(e));return t>=ps&&t<s0;}).length;if(prev>0){const p=Math.round((total-prev)/prev*100);ct=p>0?'↑ +'+p+'%':p<0?'↓ −'+Math.abs(p)+'%':'→ 持平';if(p>0)cmp.classList.add('up');if(p<0)cmp.classList.add('down');}else if(total)ct='新增';}cmp.textContent=ct;const tr=buildTrend();ChartUI.trend($('#cvTrend'),tr.data,tr.ma);$('#trendTail').textContent=tr.step>1?`按${tr.step===7?'周':'月'}聚合 · 深线为动态均线`:(tr.ma?`金线为每日 · 深线为${tr.ma}日均线`:'金线为每日用量');if(tr.data.length>=14){const a=tr.data.slice(-7).reduce((s,p)=>s+p.c,0)/7,b=tr.data.slice(-14,-7).reduce((s,p)=>s+p.c,0)/7;$('#noteTrend').textContent=`最近7个观察点均值 ${a.toFixed(1)}，此前 ${b.toFixed(1)}。`;}else $('#noteTrend').textContent=tr.data.length?`当前范围平均 ${(tr.data.reduce((s,p)=>s+p.c,0)/tr.data.length).toFixed(1)}。`:'暂无数据。';const bins=hourlyBins(R);ChartUI.hourly($('#cvHourly'),bins);const mx=Math.max(...bins),pk=bins.map((v,i)=>v===mx&&v?i:null).filter(v=>v!==null);$('#noteHourly').textContent=mx?`高峰时段 ${pk.slice(0,3).join('、')} 时，各 ${mx} 支。`:'暂无记录。';const grid=Array.from({length:7},()=>Array(24).fill(0));inR.forEach(e=>{const d=new Date(keyToTs(eventDateKey(e)));grid[(d.getDay()+6)%7][eventHour(e)]++;});ChartUI.heat($('#cvHeat'),grid);let best={v:0,r:0,c:0};grid.forEach((row,r)=>row.forEach((v,c)=>{if(v>best.v)best={v,r,c};}));$('#noteHeat').textContent=best.v?`最密集：星期${'一二三四五六日'[best.r]} ${best.c} 时，共 ${best.v} 支。`:'暂无记录。';renderWeek(inR,R);}
function renderWeek(inR,R){const sod=startOfDay(Date.now()),from=R===Infinity?firstDay():Math.max(firstDay()||sod,sod-(R-1)*DAY),sums=Array(7).fill(0),days=Array(7).fill(0),by={};inR.forEach(e=>{const k=eventDateKey(e);by[k]=(by[k]||0)+1;});for(let t=from;t<=sod;t+=DAY){const i=(new Date(t).getDay()+6)%7;days[i]++;sums[i]+=by[localDateKey(t)]||0;}const avg=sums.map((v,i)=>days[i]?v/days[i]:0),allD=days.reduce((a,b)=>a+b,0),allS=sums.reduce((a,b)=>a+b,0),base=allD?allS/allD:0;ChartUI.week($('#cvWeek'),avg,base);const dw=days.slice(0,5).reduce((a,b)=>a+b,0),de=days.slice(5).reduce((a,b)=>a+b,0),sw=sums.slice(0,5).reduce((a,b)=>a+b,0),se=sums.slice(5).reduce((a,b)=>a+b,0);$('#weekNote').textContent=events.length?`工作日日均 ${dw?(sw/dw).toFixed(1):'—'} 支 · 周末日均 ${de?(se/de).toFixed(1):'—'} 支`:'暂无数据';}
function renderHistory(reset){if(reset){histDays=14;manageMode=false;selected.clear();}const from=startOfDay(Date.now())-(histDays-1)*DAY,box=$('#histList');box.innerHTML='';const groups={};events.forEach(e=>{const t=keyToTs(eventDateKey(e));if(t<from)return;(groups[eventDateKey(e)]??=[]).push(e);});const keys=Object.keys(groups).sort().reverse();if(!keys.length)box.innerHTML='<p class="empty">这段日子还没有记录</p>';histVisible=[];keys.forEach(k=>{const arr=groups[k].sort((a,b)=>b.t-a.t),d=new Date(keyToTs(k)),sec=document.createElement('section');sec.className='hist-day';sec.innerHTML=`<header><span class="d">${cnDate(d)}</span><span class="wd">${cnWeek(d)}</span><span class="cnt">${arr.length} 支</span></header>`;arr.forEach(e=>{histVisible.push(e.id);const row=document.createElement('div');row.className='hist-row'+(manageMode?' mg':'');row.dataset.id=e.id;row.innerHTML=manageMode?`<span class="cb${selected.has(e.id)?' on':''}"></span><span class="t">${fmtHM(e.t)}</span>`:`<span class="t">${fmtHM(e.t)}</span><button class="del" data-id="${e.id}">×</button>`;sec.appendChild(row);});box.appendChild(sec);});$('#histNormBtns').hidden=manageMode;$('#histMgmtBtns').hidden=!manageMode;$('#btnSelAll').textContent=histVisible.length&&selected.size>=histVisible.length?'取消全选':'全选';$('#btnDelSel').style.display=manageMode&&selected.size?'block':'none';$('#btnDelSel').textContent=`删除所选（${selected.size}）`;$('#histOlder').style.display=events.length&&firstDay()<from?'':'none';}
function renderSettings(){const L=prefs.limit;$('#limitValue').textContent=prefs.limitTouched&&L.on?`每${L.days}天 · ${L.cigs}支`:(prefs.limitTouched?'未启用':'未设置');$('#setCount').textContent=events.length+' 条';$('#vpInfo').textContent=`视口 ${innerWidth}×${innerHeight} · 数据格式 v5`;}
function renderAll(){renderToday();renderSettings();if(cur==='stats')renderStats();if(cur==='history')renderHistory(false);}
function showPage(name){cur=name;$$('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+name));$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='today')renderToday();if(name==='stats')renderStats();if(name==='history')renderHistory(true);if(name==='settings')renderSettings();$('#scroller').scrollTop=0;}
function showUndo(ev){lastEv=ev;$('#undoTime').textContent='已记录 '+fmtHM(ev.t);$('#undoPill').classList.add('show');clearTimeout(undoTimer);undoTimer=setTimeout(()=>$('#undoPill').classList.remove('show'),5000);}
function puff(){const s=$('#stampSmoke');s.classList.remove('go');void s.offsetWidth;s.classList.add('go');}
async function recordNow(){if(recordLock)return;recordLock=true;setTimeout(()=>recordLock=false,900);const now=Date.now(),prev=events[events.length-1];if(prev&&now-prev.t<2000){toast('已忽略连续误触');return;}const ev=await addEvent(now);renderToday();$('#todayNum').classList.remove('pop');void $('#todayNum').offsetWidth;$('#todayNum').classList.add('pop');puff();$('#stampSmoke').classList.add('hot');setTimeout(()=>$('#stampSmoke').classList.remove('hot'),1200);showUndo(ev);}
function openLimit(){const L=prefs.limit;$('#limDaysIn').value=L.days;$('#limCigsIn').value=L.cigs;$('#limitOn').checked=prefs.limitTouched&&L.on;openSheet('#sheetLimit');}
async function saveLimit(){const d=parseInt($('#limDaysIn').value,10),c=parseInt($('#limCigsIn').value,10),on=$('#limitOn').checked;if(!Number.isFinite(d)||d<1||d>7||!Number.isFinite(c)||c<1||c>20){toast('天数 1–7 · 支数 1–20');return;}prefs.limit={on,days:d,cigs:c};prefs.limitTouched=true;await DB.setPref('limit',prefs);closeSheet();renderAll();toast(on?`上限 · 每${d}天 ${c} 支`:'已取消上限');}
function openBackfill(){const d=new Date(),v=`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;$('#backfillInput').value=v;$('#backfillInput').max=v;openSheet('#sheetBackfill');}
async function saveBackfill(){const v=$('#backfillInput').value,ts=v?new Date(v).getTime():NaN;if(!ts||isNaN(ts)){toast('请选择时间');return;}if(ts>Date.now()+60000){toast('时间不能在未来');return;}await addEvent(ts);closeSheet();renderAll();toast('已补记 '+fmtHM(ts));}
function buildExport(){return JSON.stringify({app:'smoke-trace',version:5,exportedAt:new Date().toISOString(),prefs,events});}
function doExport(){const d=new Date(),ds=`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,blob=new Blob([buildExport()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='smoke-trace-'+ds+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),3000);closeSheet();toast('已开始下载');}
async function doCopy(){const json=buildExport();try{await navigator.clipboard.writeText(json);toast('已复制到剪贴板');}catch{toast('复制失败，请改用下载');}closeSheet();}
async function importJSON(text){try{const data=JSON.parse(text),list=Array.isArray(data)?data:data.events;if(!Array.isArray(list))throw 0;const valid=list.filter(x=>x&&typeof x.t==='number'&&isFinite(x.t)).map(x=>({...makeEvent(x.t),...x,id:x.id||uid(),localDate:x.localDate||localDateKey(x.t),localHour:Number.isInteger(x.localHour)?x.localHour:new Date(x.t).getHours(),tzOffset:Number.isFinite(x.tzOffset)?x.tzOffset:new Date(x.t).getTimezoneOffset()}));const haveId=new Set(events.map(x=>x.id)),haveT=new Set(events.map(x=>x.t)),add=valid.filter(x=>!haveId.has(x.id)&&!haveT.has(x.t));for(const ev of add)await DB.putEvent(ev);events=events.concat(add).sort((a,b)=>a.t-b.t);if(data.prefs){prefs=mergePrefs(data.prefs);await DB.setPref('limit',prefs);}$('#importText').value='';closeSheet();renderAll();toast(add.length?`已导入 ${add.length} 条记录`:'没有需要导入的新记录');}catch{toast('内容不是有效的备份');}}
async function doClear(){if(!events.length){toast('没有数据');return;}if(!await confirmSheet('清空全部数据？',`共 ${events.length} 条记录将永久删除。建议先导出备份。`,'永久删除'))return;await DB.clearEvents();events=[];renderAll();toast('已清空');}
function bindUI(){$('#tabs').onclick=e=>{const b=e.target.closest('button[data-page]');if(b)showPage(b.dataset.page);};$('#stampBtn').onclick=recordNow;$('#undoBtn').onclick=async()=>{if(!lastEv)return;await DB.delEvent(lastEv.id);events=events.filter(x=>x.id!==lastEv.id);lastEv=null;$('#undoPill').classList.remove('show');renderAll();toast('已撤销');};$('#rangeSeg').onclick=e=>{const b=e.target.closest('button[data-r]');if(!b)return;statsRange=b.dataset.r==='all'?Infinity:+b.dataset.r;$$('#rangeSeg button').forEach(x=>x.classList.toggle('on',x===b));renderStats();};$('#limitMini').onclick=$('#limitOpen').onclick=openLimit;$('#limitSave').onclick=saveLimit;$('#btnBackfill').onclick=openBackfill;$('#backfillSave').onclick=saveBackfill;$('#btnManage').onclick=()=>{manageMode=true;selected.clear();renderHistory(false);};$('#btnDone').onclick=()=>{manageMode=false;selected.clear();renderHistory(false);};$('#btnSelAll').onclick=()=>{selected=selected.size>=histVisible.length?new Set():new Set(histVisible);renderHistory(false);};$('#btnDelSel').onclick=async()=>{if(!selected.size)return;if(!await confirmSheet('删除所选记录？',`共 ${selected.size} 条记录将永久移除。`,'删除'))return;for(const id of selected)await DB.delEvent(id);events=events.filter(x=>!selected.has(x.id));selected.clear();renderAll();};$('#histList').onclick=async e=>{const row=e.target.closest('.hist-row');if(manageMode&&row){selected.has(row.dataset.id)?selected.delete(row.dataset.id):selected.add(row.dataset.id);renderHistory(false);return;}const b=e.target.closest('.del');if(!b)return;const ev=events.find(x=>x.id===b.dataset.id);if(ev&&await confirmSheet('删除这条记录？',`${fmtMD(keyToTs(eventDateKey(ev)))} ${fmtHM(ev.t)} 的记录将被移除。`,'删除')){await DB.delEvent(ev.id);events=events.filter(x=>x.id!==ev.id);renderAll();}};$('#histOlder').onclick=()=>{histDays+=28;renderHistory(false);};$('#btnExport').onclick=()=>openSheet('#sheetExport');$('#expDownload').onclick=doExport;$('#expCopy').onclick=doCopy;$('#btnImport').onclick=()=>openSheet('#sheetImport');$('#impText').onclick=()=>{const v=$('#importText').value.trim();v?importJSON(v):toast('请先粘贴内容');};$('#impPaste').onclick=async()=>{try{$('#importText').value=await navigator.clipboard.readText();toast('已读取剪贴板');}catch{toast('读取被拒，请手动粘贴');}};$('#impFile').onclick=()=>$('#fileImport').click();$('#fileImport').onchange=e=>{const f=e.target.files[0];e.target.value='';if(!f)return;const r=new FileReader();r.onload=()=>importJSON(r.result);r.readAsText(f);};$('#btnClear').onclick=doClear;$('#mask').onclick=()=>{closeSheet();if(confirmRes){confirmRes(false);confirmRes=null;}};$$('.sheet [data-close]').forEach(b=>b.onclick=closeSheet);$('#a2hsClose').onclick=()=>{$('#a2hs').style.display='none';localStorage.setItem('st_tip','1');};document.addEventListener('visibilitychange',()=>{if(!document.hidden)renderAll();});setInterval(()=>{if(cur==='today'&&!document.hidden)renderToday();},30000);}
async function init(){await DB.open();events=(await DB.getEvents()).sort((a,b)=>a.t-b.t);prefs=mergePrefs(await DB.getPref('limit'));bindUI();const standalone=navigator.standalone===true||(matchMedia&&matchMedia('(display-mode: standalone)').matches);if(!standalone&&!localStorage.getItem('st_tip'))$('#a2hs').style.display='flex';showPage('today');if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js?v=19');reg.update();}catch(e){console.warn('SW registration failed',e);}}}
init();
