'use strict';
const ChartUI=(()=>{
  const C={ink:'#29231F',ink2:'#51483F',faint:'#7B6F63',line:'#D8CEBE',amber:'#B2762F',amber2:'#D99A45',amberD:'#754819'};
  const CF='"Source Han Serif SC","Noto Serif SC","Songti SC",Georgia,serif';
  const ctx2d=(cv,h)=>{const w=cv.clientWidth||cv.parentElement.clientWidth||330,d=Math.min(3,devicePixelRatio||1);cv.width=Math.round(w*d);cv.height=Math.round(h*d);cv.style.height=h+'px';const c=cv.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);return{c,w,h};};
  const rr=(c,x,y,w,h,r)=>{r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();};
  const heatColor=t=>{t=Math.min(1,Math.max(0,t));const st=[[239,231,210],[218,165,91],[178,118,47],[117,72,25]],seg=Math.min(2,Math.floor(t*3)),f=t*3-seg,a=st[seg],b=st[seg+1];return`rgb(${Math.round(a[0]+(b[0]-a[0])*f)},${Math.round(a[1]+(b[1]-a[1])*f)},${Math.round(a[2]+(b[2]-a[2])*f)})`;};
  const smooth=(c,pts)=>{if(pts.length<2)return;c.moveTo(pts[0].x,pts[0].y);for(let i=0;i<pts.length-1;i++){const p=pts[i],q=pts[i+1],mx=(p.x+q.x)/2;c.bezierCurveTo(mx,p.y,mx,q.y,q.x,q.y);}};
  let trendGeom=null,hourGeom=null,heatGeom=null,heatGrid=null;
  function trend(cv,data,ma){const{c,w,h}=ctx2d(cv,224),L=12,R=12,T=28,B=22,iw=w-L-R,ih=h-T-B;trendGeom={L,iw,n:data.length};if(!data.length){c.fillStyle=C.faint;c.font='13px '+CF;c.textAlign='center';c.fillText('暂无数据',w/2,T+ih/2);return;}const n=data.length,maxV=Math.max(1,...data.map(p=>p.c)),yMax=Math.max(3,Math.ceil(maxV/5)*5),X=i=>n===1?L+iw/2:L+i/(n-1)*iw,Y=v=>T+ih-v/yMax*ih;c.strokeStyle=C.line;c.setLineDash([2,4]);[yMax/2,yMax].forEach(v=>{c.beginPath();c.moveTo(L,Y(v));c.lineTo(w-R,Y(v));c.stroke();});c.setLineDash([]);const pts=data.map((p,i)=>({x:X(i),y:Y(p.c)})),g=c.createLinearGradient(0,T,0,T+ih);g.addColorStop(0,'rgba(178,118,47,.22)');g.addColorStop(1,'rgba(178,118,47,0)');c.beginPath();smooth(c,pts);c.lineTo(X(n-1),T+ih);c.lineTo(X(0),T+ih);c.closePath();c.fillStyle=g;c.fill();if(ma>0&&data.some(p=>Number.isFinite(p.m))){c.strokeStyle=C.amberD;c.lineWidth=1.5;c.beginPath();smooth(c,data.map((p,i)=>({x:X(i),y:Y(p.m)})));c.stroke();}c.strokeStyle=C.amber;c.lineWidth=2;c.beginPath();smooth(c,pts);c.stroke();c.fillStyle=C.faint;c.font='11px '+CF;c.textAlign='center';const lab=p=>{const d=new Date(p.day);return`${d.getMonth()+1}/${d.getDate()}`;};c.fillText(lab(data[0]),L+15,h-5);c.fillText(lab(data[n-1]),w-R-15,h-5);if(n>24)c.fillText(lab(data[Math.floor(n/2)]),w/2,h-5);}
  function hourly(cv,bins){const{c,w,h}=ctx2d(cv,208),L=6,R=6,T=25,B=24,iw=w-L-R,ih=h-T-B,bw=iw/24,barW=Math.min(14,bw*.55),max=Math.max(...bins,1),yMax=Math.max(3,Math.ceil(max/3)*3);hourGeom={L,bw};const peak=Math.max(...bins);bins.forEach((v,i)=>{if(!v)return;const bh=v/yMax*ih,x=L+i*bw+(bw-barW)/2,y=T+ih-bh,g=c.createLinearGradient(0,y,0,T+ih);if(v===peak){g.addColorStop(0,C.amber2);g.addColorStop(1,C.amberD);}else{g.addColorStop(0,'#C98B45');g.addColorStop(1,'#9B642A');}c.fillStyle=g;rr(c,x,y,barW,Math.max(2,bh),3);c.fill();});c.fillStyle=C.faint;c.font='11px '+CF;c.textAlign='center';[0,6,12,18].forEach(t=>c.fillText(t+'时',L+t*bw+bw/2,h-6));if(!bins.some(Boolean)){c.font='13px '+CF;c.fillText('暂无记录',w/2,T+ih/2);}}
  function heat(cv,grid){heatGrid=grid;const w0=cv.clientWidth||330,L=26,T=2,B=20,cw=(w0-L-1)/24,ch=cw*1.45,H=Math.round(T+7*ch+B),{c,w,h}=ctx2d(cv,H);heatGeom={L,T,cw,ch};let max=0;grid.forEach(r=>r.forEach(v=>max=Math.max(max,v)));c.fillStyle=C.faint;c.font='11px '+CF;c.textAlign='right';'一二三四五六日'.split('').forEach((t,i)=>c.fillText(t,L-7,T+i*ch+ch/2+4));c.textAlign='center';[0,6,12,18].forEach(t=>c.fillText(t+'时',L+t*cw+cw/2,h-5));for(let r=0;r<7;r++)for(let col=0;col<24;col++){const v=grid[r][col],x=L+col*cw+1,y=T+r*ch+1;c.fillStyle=v?heatColor(Math.sqrt(v/Math.max(1,max))):'rgba(41,35,31,.045)';rr(c,x,y,cw-2,ch-2,3);c.fill();}}
  function week(cv,avg,base){const{c,w,h}=ctx2d(cv,168),L=10,R=10,T=18,B=24,iw=w-L-R,ih=h-T-B,bw=iw/7,barW=Math.min(30,bw*.42),max=Math.max(...avg,1);if(base>0){const y=T+ih-base/max*ih;c.strokeStyle='rgba(41,35,31,.36)';c.setLineDash([2,4]);c.beginPath();c.moveTo(L,y);c.lineTo(w-R,y);c.stroke();c.setLineDash([]);}avg.forEach((v,i)=>{const bh=v/max*ih,x=L+i*bw+(bw-barW)/2,y=T+ih-bh;if(v){c.fillStyle=C.amber;rr(c,x,y,barW,Math.max(2,bh),3);c.fill();}c.fillStyle=C.faint;c.font='11px '+CF;c.textAlign='center';c.fillText('一二三四五六日'[i],L+i*bw+bw/2,h-6);});}
  return{trend,hourly,heat,week,get heatGrid(){return heatGrid;},get heatGeom(){return heatGeom;}};
})();
